mi:
    resource: "@MiBundle/Resources/config/routing.yml"
    prefix:   /mi-bundle

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

AppBundleRoute:
    resource : "@AppBundle/Resources/config/routing.yml"
    prefix   : /
