# Rutas para la Autenticación de Usuarios
login:
    path: /login
    defaults: { _controller: BlogBundle:User:login }

login_check:
    path: /login_check

logout:
    path: /logout

# Rutas del Blog
blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Entry:index }

blog_entradas:
    path:     /blog/entradas
    defaults: { _controller: BlogBundle:Default:getEntries }

blog_categorias:
    path:     /blog/categorias
    defaults: { _controller: BlogBundle:Default:getCategories }

blog_tags:
    path:     /blog/tags
    defaults: { _controller: BlogBundle:Default:getTags }

blog_index_tags:
    path:     /tags
    defaults: { _controller: BlogBundle:Tag:index }

blog_add_tag:
    path:     /tags/add
    defaults: { _controller: BlogBundle:Tag:add }

blog_delete_tag:
    path:     /tags/delete/{id}
    defaults: { _controller: BlogBundle:Tag:delete }

blog_index_category:
    path:     /categories
    defaults: { _controller: BlogBundle:Category:index }

blog_add_category:
    path:     /categories/add
    defaults: { _controller: BlogBundle:Category:add }

blog_delete_category:
    path:     /categories/delete/{id}
    defaults: { _controller: BlogBundle:Category:delete }

blog_edit_category:
    path:     /categories/edit/{id}
    defaults: { _controller: BlogBundle:Category:edit }

blog_add_entry:
    path:     /entries/add
    defaults: { _controller: BlogBundle:Entry:add }

blog_delete_entry:
    path:     /entries/delete/{id}
    defaults: { _controller: BlogBundle:Entry:delete }

blog_delete_with_tags_entry:
    path:     /entries/delete-with-tags/{id}
    defaults: { _controller: BlogBundle:Entry:deleteWithTags }
