# Rutas para la Autenticación de Usuarios
login:
    path: /login
    defaults: { _controller: BlogBundle:User:login }

login_check:
    path: /login_check

logout:
    path: /logout

# Rutas del Blog
blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

blog_entradas:
    path:     /blog/entradas
    defaults: { _controller: BlogBundle:Default:getEntries }

blog_categorias:
    path:     /blog/categorias
    defaults: { _controller: BlogBundle:Default:getCategories }

blog_tags:
    path:     /blog/tags
    defaults: { _controller: BlogBundle:Default:getTags }
