## Plantilla YAML
#  para abstraer todas las rutas del proyecto

pruebas_index:
  path     : /pruebas/{lang}/{name}/{page}                  # Pasa dos parámetros a la ruta
  methods  : [ GET ] # Podemos indicarle el tipo de método por el cual queremos pasar el o los parámetros al controlador
  # Bundle:Controlador:Método, 1re Parámetro por defecto para 'name', Parámetro por defecto para 'page'
  defaults : { _controller: AppBundle:Pruebas:index, lang: es, name:"1er parámetro por defecto", page:1 }
  requirements :
    # Con una expresión regular le indicamos reglas a cada parámetro
    name: \w+  # Solo valores Alfanuméricos
    page: \d+  # Solo valores Enteros
    lang: es|en|fr # opcion1 o opcion2 o opcion3
