## Plantilla YAML
#  para abstraer todas las rutas del proyecto

pruebas_index:
  path     : /pruebas/{lang}/{name}/{page}                  # Pasa dos parámetros a la ruta
  methods  : [ GET, POST ] # Podemos indicarle el tipo de método por el cual queremos pasar el o los parámetros al controlador
  # Bundle:Controlador:Método, 1re Parámetro por defecto para 'name', Parámetro por defecto para 'page'
  defaults : { _controller: AppBundle:Pruebas:index, lang: es, name:"1er parámetro por defecto", page:1 }
  requirements :
    # Con una expresión regular le indicamos reglas a cada parámetro
    name : '[a-zA-Z]*'            # Solo valores Alfabéticos
    page : "^[1-9][0-9]?$|^100$"  # Solo valores Enteros entre 1 y 99
    # page: "^0*(?:[1-9][0-9]?|100)$"  # Solo valores Enteros entre 0001 y 00099
    lang : es|en|fr               # opcion1 o opcion2 o opcion3

pruebas_create:
    path : /pruebas/create
    defaults : { _controller: AppBundle:Pruebas:create }

pruebas_read:
    path : /pruebas/read
    defaults : { _controller: AppBundle:Pruebas:read }

pruebas_update:
    path : /pruebas/update/{id}/{titulo}/{descripcion}/{precio}
    defaults : { _controller: AppBundle:Pruebas:update }

pruebas_delete:
    path : /pruebas/delete/{id}
    defaults : { _controller: AppBundle:Pruebas:delete }

pruebas_read_price:
    path : /pruebas/read/price/{precio}
    defaults : { _controller: AppBundle:Pruebas:readByPrice }

pruebas_read_prices:
    path : /pruebas/read/prices/{precio}
    defaults : { _controller: AppBundle:Pruebas:readByPrices }

pruebas_read_title:
    path : /pruebas/read/title/{titulo}
    defaults : { _controller: AppBundle:Pruebas:readByTitle }

pruebas_read_title_and_price:
    path : /pruebas/read/title-price/{titulo}/{precio}
    defaults : { _controller: AppBundle:Pruebas:readByTitleAndPrice }

pruebas_native:
    path : /pruebas/native/
    defaults : { _controller: AppBundle:Pruebas:nativeSql }
