AppBundle\Entity\Curso:
  properties:
    titulo:
      - NotBlank: { message: "EL título no puede estar vacío" }
      - Length:
          min: 2
          minMessage: "El título debe tener mas de dos caracteres"
    descripcion:
      - NotBlank: { message: 'La descripción del curso no puede estar vacía' }
    precio:
      - Type:
          type: numeric
          message: "El precio debe ser un valor numérico"
